spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/login_database?serverTimezone=UTC&characterEncoding=UTF-8
    username: test_admin
    password: testadmin1234
  jpa:
    hibernate:
      ddl-auto: none